apiVersion: image.openshift.io/v1
kind: Template
metadata:
  name: service-template
  annotations:
    csas/deployment.vcs-url: "git@github.com:tajne123456789/spring-boot-rest.git"
    csas/deployment.vcs-ref: "master"
    csas/deployment.vcs-root: "openshift"

parameters:
  # System parameters
  - name: SERVICE_NAME
    displayName: "Configuration Name"
    description: "Name of the deployment configuration objects"
    required: true
    value: "nia-adapter"

  - name: IMAGE_STREAM_TAG
    displayName: "Image Stream Tag"
    description: "Docker image used for deployment"
    required: true

  - name: IMAGE_STREAM_NAMESPACE
    displayName: "Image Stream Namespace"
    description: "Namespace where is source image stream defined"

    # this ID is added to config objects to distinct config versions - to prevent overwriting configuration
  - name: DEPLOYMENT_ID
    displayName: "Deployment Id"
    description: "Id string used for versioning ConfigMaps"
    generate: expression
    from: "[a-z0-9]{8}"

  - name: LOG_LEVEL
    description: "z env souboru"
    displayName: "Level of logging"
    value: ""
  
  - name: REPLICAS
    displayName: "Number of replicas"
    description: "Number of replicas"
    required: true
    value: "1"

objects:
  - apiVersion: v1
    kind: ConfigMap
    data:
      application.properties: |
        logging.level.root=${LOG_LEVEL}
    metadata:
      name: niaconfig-adapter

  - kind: Service
    apiVersion: v1
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: ${SERVICE_NAME}
      name: ${SERVICE_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${SERVICE_NAME}
      sessionAffinity: None
      type: ClusterIP

  # Route - tells what port(s) are axposed and how
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${SERVICE_NAME}"
      labels:
        app: "${SERVICE_NAME}"
    spec:
      to:
        name: "${SERVICE_NAME}"
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge

  # Deployment Config - describes how the app is deployed
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      generation: 9
      labels:
        app: ${SERVICE_NAME}
      name: ${SERVICE_NAME}
    spec:
      replicas: ${{REPLICAS}}
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 10
          intervalSeconds: 30
      selector:
        name: "${SERVICE_NAME}"
      template:
        metadata:
          labels:
            name: "${SERVICE_NAME}"
        spec:
          containers:
            - image: ' '
              name: app
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  memory: 750Mi
                limits:
                  memory: 4Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/logs
                  name: logs-volume
                - mountPath: /app/config
                  name: config-volume
                - mountPath: /app/secret
                  name: secret-volume
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: logs-volume
              emptyDir: {}
            - name: config-volume
              configMap:
                name: niaconfig-adapter
                defaultMode: 420
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - app
            from:
              kind: ImageStreamTag
              name: "${IMAGE_STREAM_TAG}"
              namespace: "${IMAGE_STREAM_NAMESPACE}"